### ISSUE TITLE
Documentation / explanation of the reason this is a fork

### ISSUE THREAD

**Issue by arthurlutz** [Catfriend1/syncthing-android#70]
It would be nice to have some sort of explanation in the README or the fdroid description https://f-droid.org/packages/com.github.catfriend1.syncthingandroid/ about why there is a fork from the original project and what interactions there are to be expected with the original project.

**Comment by hyiltiz** [comment]
Why not submit pull requests to the original one?

**Comment by Catfriend1** [comment]
There is already a description which improvements it offers on github and fdroid. If you look at the recent issues and discussion about my work and contributions you'll understand why.

**Comment by Catfriend1** [comment]
Major enhancements in this fork are:
UI explains why syncthing is running or not running according to the run conditions set in preferences.
A welcome wizard guiding you through initial setup on first launch or if mandatory prerequisites are missing like for example the storage permission.
Run condition bugs are fixed.
"Battery eater" problem is fixed.
Android 8+ support is on it's way.
Many bug fixes, enhancements and more frequent releases.

**Comment by hyiltiz** [comment]
I looked at your issues and there is only one mostly discussing logos and naming, but that still doesn't explain why pull requests aren't enough. You are perfectly eligible to create your own fork, of course, but a goal that separates your project from the original, not just some feature list, would be very helpful for users to understand what they should do.

**Comment by Catfriend1** [comment]
I dont want to sound like accusing anyone of anything cause I like the work of the original syncthing project and its developers ... Story short is I wanted to fix major bugs and fulfill feature requestes when I've time left for that. I've made a lot of PRs but the outcome wasn't "right" from my point of view.
Links:
https://forum.syncthing.net/t/syncthing-android-unofficial-beta/11920
https://forum.syncthing.net/t/folder-creation-broken-in-android-app/11885/2
https://github.com/syncthing/syncthing-android/issues/1228
https://github.com/Catfriend1/syncthing-android/issues/62

(And more)

**Comment by hyiltiz** [comment]
After going through all those forums and the links they point to, it is still unclear to me which project to follow in order to get what (goal unclear), except that your fork seems to have unit tests and more frequent release cycle.

**Comment by Catfriend1** [comment]
"WE" will deine a more defined goal If more people joined.
